services:
    rmcgirr83.topfive.listener:
        class: rmcgirr83\topfive\event\listener
        arguments:
            - @template
            - @user
            - @dbal.conn
            - @cache
            - @config
            - %core.php_ext%
            - %core.root_path%
        tags:
            - { name: event.listener }
